// ---------------------------------------------------------------------------
// Extra liquidity pair pools created on Solana Devnet (seeded 5000 / 5000).
// Each pool is a deterministic owner keypair holding two token vaults (ATAs).
// USDC/RLO is intentionally absent — it already exists as the Raydium pool.
// Generated by scripts/create-pools.mjs.
// ---------------------------------------------------------------------------
export interface PairPoolCfg {
  name: string;
  poolId: string;
  symbolA: string;
  symbolB: string;
  mintA: string;
  mintB: string;
  vaultA: string;
  vaultB: string;
  feeBps: number;
}

export const PAIR_POOLS: PairPoolCfg[] = [
  {
    name: "USDC/USDT",
    poolId: "6Anz4CPoBctHvM5UHUbFE6tJ4RAVsHCtM2p3jPt9hk7j",
    symbolA: "USDC",
    symbolB: "USDT",
    mintA: "9tW7QNDWTV2G2HEK4TZJpwEep1CFMfew2R4fUTzMKoZV",
    mintB: "8AfaGuuwj2fKpNYmn7FZFYqc6Dx4KwrWH9FjRwiBKZod",
    vaultA: "FiNxqyzyhgrR8yPMbB9wYVnikawd2zAbZ7TZeU54n22o",
    vaultB: "G2P4JdRpnijp2r8429aYktCPsV699C55DqdPeAKUhG7k",
    feeBps: 30,
  },
  {
    name: "USDT/RLO",
    poolId: "3Crmisz9x9XKJ5SaCGtrHA8sq4WxjdYAgjLeftjLD6oW",
    symbolA: "USDT",
    symbolB: "RLO",
    mintA: "8AfaGuuwj2fKpNYmn7FZFYqc6Dx4KwrWH9FjRwiBKZod",
    mintB: "375pbiYRJYS22XuHqAD6KSWQroVnF41ayoLvKtPp4Du6",
    vaultA: "AizE8p7oQXtEmCMv8eQWZjdhLQAawXxiMY3boX6q7gWB",
    vaultB: "3GDFwLTHypFh1o5zvTsZtgDrUA5cvc3FUK9BaffRmozC",
    feeBps: 30,
  },
];
